Documentation:
  Enabled: false

Layout/LineLength:
  Max: 1000

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 1000
  
Metrics/AbcSize:
  Max: 1000

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NumericPredicate:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: true